import { createHash, randomBytes } from "crypto";
import type { User } from "@prisma/client";
import { env } from "../config/env";
import { prisma } from "../lib/prisma";
import { AppError } from "../middleware/error";
import { hashPassword, verifyPassword } from "../utils/hash";
import {
  signAccessToken,
  signRefreshToken,
  verifyRefreshToken,
} from "../utils/jwt";
import { emailProvider } from "../utils/email";
import type {
  ForgotPasswordInput,
  LoginInput,
  RegisterInput,
  ResetPasswordInput,
} from "../schemas/auth.schema";

const RESET_TOKEN_TTL_MS = 60 * 60 * 1000; // 1 hour

/** Public-safe view of a User — never leak hashes or tokens. */
export interface SafeUser {
  id: string;
  organizationId: string;
  email: string;
  name: string;
  role: "ADMIN" | "AGENT";
}

interface AuthResult {
  user: SafeUser;
  accessToken: string;
  refreshToken: string;
}

function toSafeUser(user: User): SafeUser {
  return {
    id: user.id,
    organizationId: user.organizationId,
    email: user.email,
    name: user.name,
    role: user.role,
  };
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

/**
 * Mint a new access+refresh pair and persist the refresh token on the user.
 * Persisting it is what lets us rotate/revoke: only the latest refresh token is
 * valid, so a stolen older one stops working after the next refresh.
 */
async function issueTokens(
  user: Pick<User, "id" | "organizationId" | "role">,
): Promise<{ accessToken: string; refreshToken: string }> {
  const accessToken = signAccessToken({
    userId: user.id,
    organizationId: user.organizationId,
    role: user.role,
  });
  const refreshToken = signRefreshToken({ userId: user.id });
  await prisma.user.update({
    where: { id: user.id },
    data: { refreshToken },
  });
  return { accessToken, refreshToken };
}

/**
 * Register a new tenant: Organization + first ADMIN user + default BotConfig,
 * all in one transaction so a partial signup can never exist. publicApiKey is
 * generated by the schema's cuid() default on Organization.
 */
export async function register(input: RegisterInput): Promise<AuthResult> {
  const existing = await prisma.user.findUnique({
    where: { email: input.email },
  });
  if (existing) {
    throw new AppError(409, "Email already registered");
  }

  const passwordHash = await hashPassword(input.password);

  const user = await prisma.$transaction(async (tx) => {
    const org = await tx.organization.create({
      data: { name: input.organizationName },
    });
    const created = await tx.user.create({
      data: {
        organizationId: org.id,
        email: input.email,
        passwordHash,
        name: input.name,
        role: "ADMIN",
      },
    });
    await tx.botConfig.create({ data: { organizationId: org.id } });
    return created;
  });

  const tokens = await issueTokens(user);
  return { user: toSafeUser(user), ...tokens };
}

export async function login(input: LoginInput): Promise<AuthResult> {
  const user = await prisma.user.findUnique({
    where: { email: input.email },
  });
  // Same error whether the email or the password is wrong — no enumeration.
  if (!user || !(await verifyPassword(input.password, user.passwordHash))) {
    throw new AppError(401, "Invalid email or password");
  }

  const tokens = await issueTokens(user);
  return { user: toSafeUser(user), ...tokens };
}

/**
 * Rotate the refresh token: verify signature, confirm it matches the one stored
 * for the user (rejecting reused/revoked tokens), then issue a fresh pair.
 */
export async function refresh(
  token: string,
): Promise<{ accessToken: string; refreshToken: string }> {
  let userId: string;
  try {
    ({ userId } = verifyRefreshToken(token));
  } catch {
    throw new AppError(401, "Invalid or expired refresh token");
  }

  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user || user.refreshToken !== token) {
    throw new AppError(401, "Refresh token has been revoked");
  }

  return issueTokens(user);
}

export async function getMe(userId: string): Promise<SafeUser> {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) {
    throw new AppError(404, "User not found");
  }
  return toSafeUser(user);
}

/**
 * Begin password reset. Stores a hashed, time-limited token and emails the raw
 * token via the swappable provider. Always resolves the same way regardless of
 * whether the email exists, to avoid account enumeration.
 */
export async function forgotPassword(input: ForgotPasswordInput): Promise<void> {
  const user = await prisma.user.findUnique({
    where: { email: input.email },
  });
  if (!user) return;

  const rawToken = randomBytes(32).toString("hex");
  await prisma.user.update({
    where: { id: user.id },
    data: {
      resetToken: sha256(rawToken), // store only the hash
      resetTokenExpiry: new Date(Date.now() + RESET_TOKEN_TTL_MS),
    },
  });

  const resetUrl = `${env.FRONTEND_URL}/reset-password?token=${rawToken}`;
  await emailProvider.sendPasswordReset(user.email, resetUrl);
}

/**
 * Complete password reset. Validates the hashed token + expiry, sets the new
 * password, clears the reset token, and revokes any existing refresh token so
 * all sessions must re-authenticate.
 */
export async function resetPassword(input: ResetPasswordInput): Promise<void> {
  const user = await prisma.user.findFirst({
    where: {
      resetToken: sha256(input.token),
      resetTokenExpiry: { gt: new Date() },
    },
  });
  if (!user) {
    throw new AppError(400, "Invalid or expired reset token");
  }

  const passwordHash = await hashPassword(input.password);
  await prisma.user.update({
    where: { id: user.id },
    data: {
      passwordHash,
      resetToken: null,
      resetTokenExpiry: null,
      refreshToken: null, // force re-login everywhere
    },
  });
}
